### PR TITLE
Bump Closure to v20230802

### PR DESCRIPTION
**Pull request by swannodette**

### CODE REVIEW

**Comment by thheller** [comment]
FWIW I reverted the closure-compiler bump in shadow-cljs, due to it no longer compiling a couple packages that worked before. See https://github.com/thheller/shadow-cljs/issues/1170

Didn't have any issues compiling CLJS code though, so doesn't affect regular CLJS so much. Only really an issue for some npm packages. Another problem in that release was https://github.com/google/closure-compiler/issues/4151, which appears to be fixed in master, but has no release yet. I think skipping the v20231112 release is fine.

Also the breakage here is due to them renaming stuff once again, and a few leftover places renaming "modules" to "chunks". So, `compileModules` becomes `compileChunks`. Always fun ...

**Comment by swannodette** [comment]
@thheller if we bump I'm assuming that will causes annoyances for shadow?

**Comment by thheller** [comment]
It might yeah.

Usually shadow-cljs was a bit ahead, so that would get auto-picked by the usual conflict resolution. If CLJS itself is newer that will break, if people don't set up their exclusions correctly. Mostly will affect `project.clj` and `deps.edn` users, as `shadow-cljs.edn` itself guards against that.

**Comment by swannodette** [comment]
@thheller ok, that's undesirable. I'll downgrade before merging this.

**Pull request merged**
