### PR TITLE
CLJS-2893 seq should use .-length rather than alength

### PR DESCRIPTION
**Pull request by cellularmitosis**
This was suggested by @mfikes (see https://twitter.com/mfikes/status/1037182264294207489) as a newb-friendly first PR.  I believe I saw in another tweet earlier this week that this speeds things up a bit.

See also https://dev.clojure.org/jira/browse/CLJS-2893

### CODE REVIEW

**Comment by cellularmitosis** [comment]
Just filled out the contributor agreement https://secure.na1.echosign.com/public/hostedForm?formid=95YMDL576B336E

**Comment by cellularmitosis** [comment]
```
$ lein test
...
Ran 142 tests containing 649 assertions.
0 failures, 0 errors.
```

**Comment by mfikes** [comment]
Hah, someone beat you to that one. :)
Anyway, ClojureScript contributions are done via patches in JIRA. See https://clojurescript.org/community/contributing and https://clojurescript.org/community/patches

**Comment by pepasflo** [comment]
Oops, thanks @mfikes !

**Pull request closed without merging**
