### PR TITLE
No 1.10.312 jar?

### PR DESCRIPTION
**Pull request by ilovezfs**
Is there supposed to be a https://github.com/clojure/clojurescript/releases/download/r1.10.312/cljs.jar

### CODE REVIEW

**Comment by ilovezfs** [comment]
Specifically https://github.com/Homebrew/homebrew-core/blob/master/Formula/clojurescript.rb#L4 cannot be upgraded to 1.10.312 without the jar :)

**Comment by mfikes** [comment]
Oh, by the way @ilovezfs, ClojureScript doesn't take PRs. (Patches are filed via JIRA.) In this case, I think it was just an oversight of David's (we wouldn't be reverting to say 1.10.238 is the latest).

**Comment by ilovezfs** [comment]
@mfikes yeah I'm just trying to get the jar posted so we can upgrade in Homebrew! I assume this PR is DOA.

**Comment by ilovezfs** [comment]
The 1.10.312 jar was uploaded! Thanks to whoever did that.

**Pull request closed without merging**
