### PR TITLE
workflow: update setup-clojure and use latest cli

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
@swannodette side note, the latest `cljs.jar` did not get uploaded to the latest release. (relates to Homebrew/homebrew-core#77249)

**Comment by swannodette** [comment]
We don't take PRs, thanks for the bumps but this not a high priority thing unless it's fixing something that actually broken.

**Comment by chenrui333** [comment]
@swannodette totally understandable.

**Comment by chenrui333** [comment]
looks like the jar is there in the latest release now. thanks!!

**Pull request closed without merging**
