### PR TITLE
update README to 1.7.122

### PR DESCRIPTION
**Pull request by cap10morgan**
If it's about updating the README to display the latest version on the GitHub page, can that be a pull request?

### CODE REVIEW

**Comment by danielcompton** [comment]
@cap10morgan 1.7.122 isn't marked stable AFAICT so this shouldn't be applied, and I'm 99.9% certain that a pull request wouldn't be taken, even for a README change.

**Comment by cap10morgan** [comment]
@danielcompton In what way is it "not marked stable"? It is reported as the latest release of ClojureScript in every way except for this README.

**Comment by danielcompton** [comment]
It's marked as pre-release.

screenshot of safari 6-10-15 5 39 16 pm

**Comment by swannodette** [comment]
ClojureScript doesn't take pull requests. We occasionally cut pre-release Maven artifacts for users who need quick fixes without announcing them.

**Pull request closed without merging**
